apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  namespace: socialmedia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: search-service
  template:
    metadata:
      labels:
        app: search-service
    spec:
      containers:
        - name: search-service
          image: your-dockerhub-username/search-service:latest
          ports:
            - containerPort: 3004
          env:
            - name: REDIS_HOST
              value: redis
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"