apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-service
  namespace: socialmedia
spec:
  replicas: 2
  selector:
    matchLabels:
      app: media-service
  template:
    metadata:
      labels:
        app: media-service
    spec:
      containers:
        - name: media-service
          image: your-dockerhub-username/media-service:latest
          ports:
            - containerPort: 3003
          env:
            - name: REDIS_HOST
              value: redis
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"